services:
  node:
    container_name: node
    build: ./back-end
    restart: always
    ports:
      - 4500:4500
    env_file:
      - back-end/.env
  
  react:
    container_name: react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html
  
  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs
  
  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - react-volume:/var/www/html
      - ssl-certs:/certs
    depends_on:
      - node
      - react

volumes:
  react-volume:
  ssl-certs:
